#!/usr/bin/env bash
# Install dotfiles with dotbot.
# Upstream: https://github.com/anishathalye/dotbot/blob/master/tools/git-submodule/install

set -e

CONFIG=".config/dotbot/install.conf.yaml"
REPOS_DIR=".local/repos"
DOTBOT_DIR="${REPOS_DIR}/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
# git submodule update --init --recursive "${DOTBOT_DIR}"
# Actually, initialize all submodules in my dotfiles as they are needed by not dotbot but shell confs etc. This is especially needed to be automated here for GitHub codespaces.
git submodule update --init --recursive "${REPOS_DIR}"


"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
