# Brewfile for general base systems. Host specifics can be found in .Brewfile.$HOSTNAME files.
# Manual: https://docs.brew.sh/Manpage#bundle-subcommand
# Modeline {
#    vi: foldmarker={,} foldmethod=marker foldlevel=0 tabstop=8 ft=brewfile:
#    The syntax highlight via vim plugin https://github.com/bfontaine/Brewfile.vim
# }

# Taps {
    tap 'beeftornado/rmtree' # rmtree: remove brew package's dependencies with $(brew rmtree <package>).
    tap 'homebrew/autoupdate' # https://github.com/Homebrew/homebrew-autoupdate
# }

# Formula: default {
    brew 'ack'
    brew 'as-tree'	# A tree view of the contents of a directory. $(fd ... | as-tree)
    brew 'aspell'
    brew 'bash'
    brew 'bash-completion'
    brew 'bashdb'
    brew 'bat'
    brew 'bat-extras'
    brew 'broot'
    brew 'cheat'
    brew 'cloc'
    brew 'cmatrix'
    brew 'colordiff'
    brew 'coreutils'		# Note that some gnu pakcages comes with g-prefix in the bin names. The default names are set up in $PATH in $XDG_CONFIG_HOME/shell/commons.
    brew 'cormacrelf/tap/dark-notify'    # To detect chagnes in OS light/dark appearens. Used by https://github.com/cormacrelf/dark-notify/
    brew 'cowsay'
    brew 'ctags'
    brew 'curl'
    brew 'dfc'
    brew 'dos2unix'
    brew 'fd'			# A powerful alternative to find.
    brew 'findutils'
    brew 'fswatch'		# For macos_appearance_monitor.sh
    brew 'fzf'
    brew 'gawk'
    brew 'gh'
    brew 'ghq'
    brew 'git'
    brew 'gnu-getopt'
    brew 'gnu-indent'
    brew 'gnu-sed'
    brew 'gnu-tar'
    brew 'gnupg'
    brew 'gnutls'
    brew 'graphviz'
    brew 'grep'
    brew 'grip'
    brew 'htop'
    brew 'httpie'
    brew 'iftop'
    brew 'imagemagick'
    brew 'ipcalc'
    brew 'jq'
    brew 'less'
    brew 'mosh'
    brew 'ncdu'
    brew 'neovim'
    brew 'netcat'
    brew 'nmap'
    brew 'npm'
    brew 'octave'
    brew 'pdfgrep'
    brew 'peco'
    brew 'pidof'
    brew 'pipx'		# To manage globally installed cli tools from pip.
    brew 'python'
    brew 'readline'
    brew 'rename'       # a.k.a. rename.pl
    brew 'ripgrep'	# Faster than grep, ack, ag.
    brew 'rsync'
    brew 'sl'
    brew 'source-highlight'
    brew 'switchaudio-osx'
    brew 'telnet'
    brew 'texlab' # Language server for LaTeX
    brew 'tig'
    brew 'tmux'
    brew 'tree'
    brew 'unar'
    brew 'unzip'
    brew 'urlview'        # for tmux link opening
    brew 'w3m'
    brew 'watch'
    brew 'wget'
    brew 'xz'
    brew 'zip'
    brew 'zsh'
    brew 'zsh-completions'
    brew 'zsh-syntax-highlighting'
# }

# Formula: optional {
=begin
    brew 'antiword'
    brew 'bashdb'
    brew 'ccls'
    brew 'cgdb'
    brew 'checkbashisms'
    brew 'cmake'
    brew 'colormake'
    brew 'colorsvn'
    brew 'cpanminus'
    brew 'cscope'
    brew 'daemonize'
    brew 'elinks'
    brew 'emacs'
    brew 'ffmpeg2theora'
    brew 'go'
    brew 'gopls'
    brew 'irssi'
    brew 'jsonlint'
    brew 'knock'
    brew 'llvm'
    brew 'mercurial'
    brew 'multitail'
    brew 'mutt'
    brew 'ncftp'
    brew 'nethogs'
    brew 'node'
    brew 'notmuch'
    brew 'offlineimap'
    brew 'openvpn'
    brew 'pastebinit'
    brew 'postgresql'
    brew 'pv'
    brew 'reattach-to-user-namespace'
    brew 'swiftlint'
    brew 'task'
    brew 'tasksh'
    brew 'tigervnc-viewer'
    brew 'valgrind'
    brew 'wakeonlan'
    brew 'wego'
    brew 'zenity'
=end
# }

# Cask: default {
    cask 'amethyst'
    cask 'appcleaner'
    cask 'clipy'
    cask 'dash'
    cask 'electric-sheep'
    cask 'firefox'
    cask 'gimp'
    cask 'google-chrome'
    cask 'iterm2'
    cask 'libreoffice'
    cask 'scroll-reverser'
    cask 'sensiblesidebuttons'    # Need to manually add it to System Preferences > Users & Groups > Login items
    cask 'spotify'
    cask 'the-unarchiver'
    cask 'vimr'
    cask 'vlc'
# }

# Cask: optional {
=begin
    cask 'adium'
    cask 'android-studio'
    cask 'atom'
    cask 'audacity'
    cask 'audio-hijack'
    cask 'awareness'
    cask 'background-music'
    cask 'bankid'
    cask 'burn'
    cask 'caffeine'
    cask 'cheatsheet'
    cask 'clamxav'
    cask 'colloquy'
    cask 'cyberduck'
    cask 'docker'
    cask 'eclipse-ide'
    cask 'epic-games'
    cask 'eqmac'
    cask 'fl-studio'
    cask 'flip4mac'
    cask 'franz'
    cask 'freshback'
    cask 'google-drive'
    cask 'gpg-suite'
    cask 'handbrake'
    cask 'insomnia'
    cask 'insync'
    cask 'intellij-idea-ce'
    cask 'itsycal'
    cask 'karabiner-elements'
    cask 'keepassxc'
    cask 'keybase'
    cask 'livereload'
    cask 'macvim'    # Prefer macvim cask to formula. Both provide MacVim.app but only the cask installs it to /Applications. Spotlight used to find both locations, but no only at /Applications. https://github.com/macvim-dev/macvim/issues/450#issuecomment-570202139
    cask 'max'
    cask 'microsoft-excel'
    cask 'microsoft-outlook'
    cask 'microsoft-powerpoint'
    cask 'microsoft-word'
    cask 'mp3tag'
    cask 'name-mangler'
    cask 'origin'
    cask 'pdftotext'
    cask 'perian'
    cask 'postman'
    cask 'prey'
    cask 'pycharm-ce'
    cask 'qr-journal'
    cask 'rambox'
    cask 'rekordbox'
    cask 'robo-3t'
    cask 'semulov'
    cask 'send-to-kindle'
    cask 'skype'
    cask 'slack'
    cask 'sound-control'
    cask 'spectacle'
    cask 'spotify-notifications'
    cask 'steam'
    cask 'stretchly'
    cask 'switch'     # Audio format converter
    cask 'thunderbird'
    cask 'tor-browser'
    cask 'tunnelblick'
    cask 'veracrypt'
    cask 'virtualbox'
    cask 'wireshark'
    cask 'xee'
    cask 'zoom'
=end
# }

# Mas: default {
# https://github.com/mas-cli/mas
# Format: mas "Human Readable Name Can Be Whatever", id:<id>
# Unfortunately this <appleiId> must have manually downloaded all apps one time before they can be installed with mas. Find <id> with
# $ mas search <app>
    mas  'Brother iPrint&Scan', id: 1193539993  # Image Capture.app does not work for Brother DCP-7070DW
    mas  'Shazam', id: 897118787
    mas  'Todoist', id: 585829637
# }

# Mas: optional {
=begin
    mas 'GamePad Companion', id: 428799479
    mas 'Irvue', id: 1039633667
    mas 'Microsoft To Do', id: 1274495053
    mas 'MuteMyMic', id: 456362093
    mas 'Neural Mix Pro', id: 1527105121
    mas 'SwordSoft Screenink Free', id: 953841977
    mas 'WeatherBug', id: 1059074180
    mas 'WhatsApp Desktop', id: 1147396723
    mas 'Xcode', id: 497799835
=end
# }

# Development: Java {
=begin
    brew 'java'
    brew 'maven'
    brew 'gradle'
    brew 'ant'

    tap 'adoptopenjdk/openjdk'
    brew 'adoptopenjdk11'
=end
# }

# Development: Python {
=begin
    brew 'ipython'
    brew 'pyright' # Language Server for python https://langserver.org/
    brew 'python@2'
=end
# }

# QuickLook Plugins {
# Reference: https://github.com/sindresorhus/quick-look-plugins
    #brew 'qlimagesize'		# QuickLook plugin for image metadata. Not working on macOS Catalina: https://github.com/Nyx0uf/qlImageSize/issues/45
    #brew 'qlvideo'		# QuickLook plugin for video files. Not working on macOS catalina: https://github.com/Marginal/QLVideo/issues/92
    brew 'apparency'		# QuickLook plugin for Applications
    brew 'qlcolorcode'		# Colorize source code
    brew 'qlmarkdown'		# Markdown preview
    brew 'qlstephen'		# View files without extension.
    brew 'quicklook-json'	# QuickLook plugin for JSON files
# }

# Misc {
# cryfs {
# Reference: https://www.cryfs.org/#download https://github.com/cryfs/cryfs
#cask 'osxfuse'
#brew 'cryfs/tap/cryfs'
# }

# Fonts {
    tap 'homebrew/cask-fonts'

    # Programming fonts {
    cask 'font-terminus'
    cask 'font-inconsolata'
    brew 'svn' # Dependency for font'source-code-pro
    cask 'font-source-code-pro'
    cask 'font-hack'
    cask 'font-dm-mono'
    # }

    tap 'colindean/fonts-nonfree'
    cask 'font-microsoft-office'
# }

# SSHFS {
# Reference: https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh
#brew 'osxfuse'
#brew 'sshfs'
# Now you can mount like this:
# $ sudo mkdir -p /mnt/sshfs
# $ sudo sshfs -o allow_other,defer_permissions user@host:/ /mnt/sshfs
# }

# }
