#!/usr/bin/env zsh
# Git overlay which adds a command to cd to the root of a git repo.

if [ "$1" = root ]; then
	# Try get root from git submodule:
	local root="$(command git rev-parse --show-superproject-working-tree)"
	# Else we're in the main repo already:
	# --show-cdup will not take us to the root if we came here from a symlink.
	#test -n "$root" || root="$($gitbin rev-parse --show-cdup)"
	# Instead get full path with --show-to-level https://stackoverflow.com/q/39746533/265508
	test -n "$root" || root="$(command git rev-parse --show-toplevel)"
	[ -n "$root" ] && cd "$root"
else
	command git $@
fi
