#!/usr/bin/env zsh
# Check if we have a cmd in PATH.
# Prefer inlinin like `if (( $+commands[CMD] )); then` to save shell startup time. These calls adds up!

local cmd="$1"

#type "$cmd" >/dev/null 2>&1

# ZSH way should be faster in theory. In practice; not sure.
(( $+commands[$cmd] ))
