#!/usr/bin/env zsh
# Sleep specified time and then shut down
# Usage: sleep_shutdown 3h
# Usage: sleep_shutdown 2d

time="$1"
if [[ -z "$time" ]]; then
    echo "Missing argument time e.g. 3h"
    return 1

fi
cmd_sleep=sleep
if has_command gsleep;
	cmd_sleep=gsleep
fi

"$cmd_sleep" $time && shutdown -h now
