#!/usr/bin/env zsh
# Wrapper around the classic 'vi with ack' with search highlighting.
# Usage example: viack -i "search_term
# Last argument is the search string. Preceding arguments are for ack.

local search
# Get the last argument. Reference: https://stackoverflow.com/a/1853993/265508
for search; do true; done
vi="$(vi_path)"
"$vi" -p $(ack -l $@) -c 1 +/$search  # Go to first line then search downwards.
