# Global Gems to install.
# NOTE asdf used ../gem/asdf-default-gems.txt
# Modeline {
# vi: foldmarker={,} foldmethod=marker foldlevel=0 ft=ruby
# }
# As it has non-standard name, use as:
# $ BUNDLE_GEMFILE=$HOME/.Gemfile bundle install
source 'https://rubygems.org'

gem 'rb-readline' # To get readline support in irb(1).

group :development do
  gem 'rubocop'   # Works well with ALE.
  gem 'solargraph' # LSP
end
