# Global Gems to install.
# Modeline {
# vi: foldmarker={,} foldmethod=marker foldlevel=0 ft=ruby:
# }
# As it has non-standard name, use as:
# $ BUNDLE_GEMFILE=$HOME/.Gemfile bundle install
source 'https://rubygems.org'

gem 'rb-readline' # To get readline support in irb(1).

group :development do
  gem 'solargraph' # LSP
  gem 'rubocop'   # Works well with ALE.
end
